[cmp]
icon_file = ""
icon_folder  = ""
icon_command = ""

[which]
separator = " "

[notify]
icon_info  = ""
icon_warn  = ""
icon_error = ""

[mgr]
border_symbol = " "

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[indicator]
preview = { reversed = true }
padding = { open = " ", close = " " }

[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[filetype]
rules = [
  # Image
  { mime = "image/*", fg = "yellow" },
  # Media
  { mime = "{audio,video}/*", fg = "magenta" },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },
  # Document
  { mime = "application/{pdf,doc,rtf}", fg = "cyan" },
  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "gray" },
  # Special file
  { url = "*", is = "orphan", bg = "red" },
  { url = "*", is = "exec"  , fg = "green", bold = true },  # bold
  # Dummy file
  { url = "*", is = "dummy", bg = "red" },
  { url = "*/", is = "dummy", bg = "red" },
  # Fallback
  { url = "*/", fg = "blue", bold = true }  # bold
]
