[cmp]
icon_file = ""
icon_folder  = ""
icon_command = ""

[which]
separator = " "

[notify]
icon_info  = ""
icon_warn  = ""
icon_error = ""

[mgr]
border_symbol = " "

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[indicator]
preview = { reversed = true }
padding = { open = " ", close = " " }

[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
