set -g aggressive-resize 1
set -g base-index 1
set -g pane-base-index 1
set -g clock-mode-style 24

set -g default-terminal 'xterm-256color'
set -s escape-time 0
set -g history-limit 10000

set -g focus-events on
set -g mouse on
set -g renumber-windows on
set -g set-titles on
set -g status-interval 10
if-shell -b '[ "$(uname)" = "Darwin" ]' \
  'set -g status-right "#(whoami)@#(hostname) | #(sysctl -n vm.loadavg | cut -f2 -d \" \") | %H:%M "'
if-shell -b '[ "$(uname)" = "Linux" ]' \
  'set -g status-right "#(whoami)@#(hostname) | #(cut -f1 -d \" \" < /proc/loadavg) | %H:%M "'
set -g pane-active-border-style fg=cyan
set -g status-style fg=black,bg=cyan
set -ga terminal-overrides ",xterm-256color:Tc"

set -g mode-keys vi
set -g status-keys vi

unbind C-b
set -g prefix C-x
bind C-x send-prefix

unbind -T copy-mode-vi v
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X rectangle-toggle
if-shell -b '[ "$(uname)" = "Darwin" ]' \
  'bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"' \
  'bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"'
if-shell -b '[ "$(uname)" = "Linux" ]' \
  'bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"' \
  'bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "wl-copy"'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind N swap-window -t +1\; select-window -t +1
bind P swap-window -t -1\; select-window -t -1
